### PR TITLE
R113 merge in AB#55704 fix brand logo and title position for iphones

### PR DESCRIPTION
**Pull request by phudson-he**
To get brand icon/title position fixes for iPhone's in keystone/release-1.1.3 branch

### CODE REVIEW

**Comment by phudson-he** [comment]
@RobOatesHistoricEngland Just a fyi apart from checking the position of the top left logo in a browser, with left nav expanded or collapsed, this issue was only viewable on an iPhone device using Browserstack

**Review by RobOatesHistoricEngland — APPROVED** [review]
Looks good.

**Review by Rehaan-Arif — APPROVED** [review]
Tested successfully

**Review by aj-he — APPROVED** [review]
looks good

**Pull request merged**
