### PR TITLE
R112 merge in AB#52727 branded landing page

### PR DESCRIPTION
**Pull request by phudson-he**
To merge in the branding changes for the landing page, together with the login page branding changes

### CODE REVIEW

**Comment by csmith-he** [comment]
Looking good.  Just wondering if

image

Should be Website **of** The Greater London Historic Environment Record

**Comment by phudson-he** [comment]
@csmith-he Yes you are correct. Just confirmed that Stu will need to have a look at the page once its released, to update images/videos/ links etc, so they are not final yet.

**Review by csmith-he — APPROVED** [review]
Approving as loads fine with new layout and format, on the understand that some content will be changed at a later date subject to feedback from Stu.

**Review by Rehaan-Arif — APPROVED** [review]
Tested Successfully

**Review by aj-he — APPROVED** [review]
Looks good

**Pull request merged**
