### PR TITLE
adds updated letter content

### PR DESCRIPTION
**Pull request by aj-he**
updated letter content as per #902 and PR https://github.com/archesproject/arches-her/pull/910

### CODE REVIEW

**Review by csmith-he — COMMENTED** [review]
@aj-he 

The following templates seem to be slightly different in the Assessment of Significance & Impact section.  Is this expected?

- Two-Stage Letter
- Pre-app Predetermination letter
- Pre-App Recommend Condition letter
- Predetermination Letter

**Comment by aj-he** [comment]
@StucakeGLHER can you confirm the observations made by @csmith-he are expected? The details you passed to me for the pull request to Farallon are below for convenience:

- Change Draft London Plan to London Plan
- Update NPPF 2019 to 2021, and the paragraph numbers to the new numbers
- Changed Advisor to Adviser, and
- Went through the static text changing paragraph font to Source Sans Pro Light where it was Source Sans Pro.

**Comment by StucakeGLHER** [comment]
@csmith-he @aj-he Hi,  is this that some of the letters have <Archaeological Priority Area> as well as ,Assessment of Significance>?  The letters are as Laura created them, so I hope thay are still correct.  Adam, one of the advisers, is going through Arches from a planning angle, so I would hope that if anything is not as it should be, he'll pick it up.

**Comment by csmith-he** [comment]
@StucakeGLHER, @aj-he 

To clarify, in this pull request, the section I'm flagging up looks like:

image

but in the templates attached to the Issue in the Arches Issues log, it looks like:

image

**Comment by StucakeGLHER** [comment]
@csmith-he @aj-he Okay, I'm not sure then.  I'll need to try and work out what Laura was trying to make happen here, and whether it was to just copy what had happened in HBSMR.  I might need to ask Adam, one of the advisers, for help with this as I don't want to give you the wrong answer.

**Comment by aj-he** [comment]
@csmith-he I clarified with @StucakeGLHER  what is happening here. The older templates with blue were showing the logic needed to display the different states. This has now been removed so it does not appear in the letters. The Assessment of Significance does work as expected in his and @rlwilliamss testing.

**Comment by aj-he** [comment]
This has now come from master so closing this PR

**Pull request closed without merging**
