### PR TITLE
Letters - format standardisation etc. AB#52575

### PR DESCRIPTION
**Pull request by RobOatesHistoricEngland**
Bolted on to [AB#52575](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52575).

Probably didn't need to include all as this stage in the process?

### CODE REVIEW

**Comment by aj-he** [comment]
@RobOatesHistoricEngland you only need me and @Rehaan-Arif involved if you are targeting a release branch. I'll remove us for this one.

**Comment by csmith-he** [comment]
@RobOatesHistoricEngland Ticket 52575 only relates to WSI Approval Letter but all templates appear to have been changed.

Could you give me a general idea as to what exactly I'm checking here?  Normally I'd check the diff but that's not possible with these templates.  Cheers.

**Comment by RobOatesHistoricEngland** [comment]
@csmith-he Assessment of Significance has been added to Condition Satisfied Letter and the following checks/changes made across all letter templates
- Remove extra spaces at the top of the letter, between the logo and <Name of person consulting>
- All header labels such as "Your Ref:" and the field have had a non-breaking space inserted (Ctrl+Shift+Space)
- Remove 93 spaces before <Completion Date> - using tabs instead
- <Contact Name> uses same font and style
- <Consultation Name> and <Proposal Description> using same font/style
- <Casework Officer> using same font/style
- Embedded fields such as <Mitigation> have the same font/style
- Double spaces in static text in the template have been removed - think this was present in just one template
- Track changes removed
-  Spacing between "Our Ref:" and "Contact" have been made consistent (one blank line)
- Letter title to use same font/style

**Review by csmith-he — APPROVED** [review]
All templates look good to me

**Pull request merged**
