### PR TITLE
#AB50691 Add Advice to Consultation Details Report 

### PR DESCRIPTION
**Pull request by csmith-he**
#AB50691

Adds Advice section to Details page for Consultation report
Actual file changed consultation.htm (other files relate to renaming issue)
Expand/collapse toggle added for Advice and Contacts sections

### CODE REVIEW

**Comment by csmith-he** [comment]
@aj-he - Adding you as a reviewer so you can confirm when you're happy for this to be pulled into the 1.0.6 branch

**Comment by aj-he** [comment]
@csmith-he this has moved to release 1.1.0. Once 1.0.6 release are puled into release-1.1.0 that should sort the conflicts.

**Comment by aj-he** [comment]
switching base branch to 1.0.7 and then back to 1.1.0 to recalculate diff

**Review by aj-he — APPROVED** [review]
approved. adding to release 1.1.0

**Pull request merged**
