### PR TITLE
Standardise all letter templates and add assessment of significance and all action scope notes

### PR DESCRIPTION
**Pull request by RobOatesHistoricEngland**
Multiple changes to the letter templates - mainly the addition of Assessment of Significance and format changes. The supplied updated changes from the business were then rationalised to address the following:

Remove extra spaces at the top of the letter, between the logo and "Name of person consulting"
All header labels such as "Your Ref:" and the field have had a non-breaking space inserted (Ctrl+Shift+Space)
Remove 93 spaces before "Completion Date" - using tabs instead
"Contact Name" uses same font and style
"Consultation Name" and "Proposal Description" using same font/style
"Casework Officer" using same font/style
Embedded fields such as "Mitigation" have the same font/style
Double spaces in static text in the template have been removed - think this was present in just one template
Track changes removed
Spacing between "Our Ref:" and "Contact" have been made consistent (one blank line)
Letter title to use same font/style
For additional action/mitigation types, scope notes was also added.

[AB#52574](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52574)
[AB#52575](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52575)
[AB#52576](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52576)
[AB#52577](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52577)
[AB#52578](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52578)
[AB#52749](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52749)
[AB#52765](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52765)
[AB#52766](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52766)
[AB#52767](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52767)
[AB#52768](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52768)
[AB#52769](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52769)
[AB#52770](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52770)
[AB#52771](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52771)
[AB#52772](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/52772)
[AB#54681](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/54681)

### CODE REVIEW

**Review by csmith-he — APPROVED** [review]
Templates all look good to me

**Comment by RobOatesHistoricEngland** [comment]
@csmith-he Could you check Blank Advisor Letter and WSI Amend Letter - changed reference to `Assessment of Significance`. Plus all templates now have the carriage return removed following "\<Assessment of Significance\>" field tag.

**Review by csmith-he — APPROVED** [review]
I'm happy the new changes are showing as expected both as template and also with letters generated using those templates

**Review by Rehaan-Arif — APPROVED** [review]
Tested Successfully

**Review by aj-he — APPROVED** [review]
Looks good

**Pull request merged**
