### PR TITLE
"Batch Create" management command AB#78898

### PR DESCRIPTION
**Pull request by RobOatesHistoricEngland**
[AB#78898](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/78898)

Management command that will use the bearer token, if one is supplied; alternatively the username and password. Need to specify the counts too. If all is well, a batch number will be returned.

```shell
> python manage.py hapi authenticate --user "rob.oates" --password "P@55w0rd!"
> 302|Jb7xhA9fTsYRjdEefkCwurPhs0zClyO9pfmj37MD9236eec5

python manage.py hapi batch_create --bearer_token "302|Jb7xhA9fTsYRjdEefkCwurPhs0zClyO9pfmj37MD9236eec5"
    --count '{"total_count": 20, "published_count": 18, "submitted_count": 4}'
> 281
```
or...

```
> python manage.py hapi batch_create --user "rob.oates" --password "P@55w0rd!" 
    --count '{"total_count": 20, "published_count": 18, "submitted_count": 4}'
> 282
```

### CODE REVIEW

**Review by khodgkinson-he — APPROVED** [review]
Looks Good!  ^_^

**Review by gouthamrandhi — APPROVED** [review]
Tested the changes successfully

**Review by khodgkinson-he — APPROVED** [review]
Tightening input validation is double-plus good!  ^_^

**Review by aj-he — COMMENTED** [review]
you are using print instead of logger in a number of areas

**Pull request merged**
