### PR TITLE
AB#61457 Upgrade index page

### PR DESCRIPTION
**Pull request by phudson-he**
Upgrade arches-her dev/7.5.x with current HE branded index page, while maintaining any new knockout and js

[AB#61457](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/61457)

### CODE REVIEW

**Comment by phudson-he** [comment]
@aj-he I've fixed the icon alignment issue, made more SASS :) and added some js to reset the expanded menu when no longer viewing on mobile widths.

**Comment by phudson-he** [comment]
@aj-he I've finished adding more colour variables. Just to note I've not touched the cookie management css in the project SASS files as thats supplied by the third party cookie company etc. Ready for re-review.

**Comment by aj-he** [comment]
@phudson-he all cookie control stuff will need to be removed as that is HE only. We could probably do that in the next index page ticket

**Comment by aj-he** [comment]
@phudson-he can I ask you to add the following to .gitignore

```
arches_her/media/build
arches_her/media/node_modules
```

**Comment by aj-he** [comment]
@phudson-he updated the AB ticket with details of an outstanding misalignment.

**Comment by phudson-he** [comment]
@aj-he I've fixed the menu animation issue. Had to do a few things but it boils down to the version of bootstrap we're using adds a .collapsing class to the nav which can be simply hidden, as we aren't displaying transitions anyway due to accessibility.

**Comment by phudson-he** [comment]
...also added those entries into .gitignore

**Review by aj-he — APPROVED** [review]
Works great!

**Pull request merged**
